# Generated by Django 3.1.4 on 2020-12-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLIENT', 'Client'), ('REVENDEUR', 'Revendeur'), ('GESTIONNAIRE', 'Gestionnaire'), ('MEDECIN', 'Medecin'), ('PATIENT', 'Patient'), ('FOURNISSEUR', 'Fournisseur'), ('COMPANY', 'Company')], max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prénom')),
                ('contact', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de Téléphone')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Adresse Email')),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(choices=[('GENERIQUE', 'GENERIQUE'), ('SPECIALITE', 'SPECIALITE')], default='GENERIQUE', max_length=30)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nom du produit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localite', models.CharField(choices=[('ZANTIEBOUGOU', 'Zantiebougou'), ('KATI FALADIE', 'Kati Faladie')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qteEntry', models.IntegerField(verbose_name='Quantité Entrée')),
                ('qteSort', models.IntegerField(verbose_name='Quantite Sortie')),
                ('qteRest', models.IntegerField(verbose_name='Quantite Restant')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fouraso.product')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fouraso.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qteCommande', models.IntegerField(verbose_name='Quantité')),
                ('price_unitaire', models.DecimalField(decimal_places=2, max_digits=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fouraso.person')),
                ('product', models.ManyToManyField(related_name='product', to='Fouraso.Product')),
            ],
        ),
    ]
