# Generated by Django 3.1.4 on 2020-12-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fouraso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='product',
            field=models.ManyToManyField(to='Fouraso.Product'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
